// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqdVaH_-xKCnpg2-yS9MDCZpB_LcVZcfU',
    appId: '1:799043029018:web:584b7dbd8e9e10a50429a3',
    messagingSenderId: '799043029018',
    projectId: 'homy-3693e',
    authDomain: 'homy-3693e.firebaseapp.com',
    databaseURL: 'https://homy-3693e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homy-3693e.appspot.com',
    measurementId: 'G-QH9DRRNKNV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKwlUq-XH6hsggwjjSWCkP-728FmmFSo',
    appId: '1:799043029018:android:53e3741429d8406d0429a3',
    messagingSenderId: '799043029018',
    projectId: 'homy-3693e',
    databaseURL: 'https://homy-3693e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homy-3693e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUeNdXDo0SLTv8sNQLcp5p7s_PiGp9hXw',
    appId: '1:799043029018:ios:ba5abce69a8ff4ad0429a3',
    messagingSenderId: '799043029018',
    projectId: 'homy-3693e',
    databaseURL: 'https://homy-3693e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homy-3693e.appspot.com',
    androidClientId: '799043029018-ah2hcl60ih400be59f9bu1rsehsf4e1a.apps.googleusercontent.com',
    iosClientId: '799043029018-ddodu4vvc4kt5okvd8ejh4vr867b2323.apps.googleusercontent.com',
    iosBundleId: 'com.example.oscar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUeNdXDo0SLTv8sNQLcp5p7s_PiGp9hXw',
    appId: '1:799043029018:ios:ba5abce69a8ff4ad0429a3',
    messagingSenderId: '799043029018',
    projectId: 'homy-3693e',
    databaseURL: 'https://homy-3693e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homy-3693e.appspot.com',
    androidClientId: '799043029018-ah2hcl60ih400be59f9bu1rsehsf4e1a.apps.googleusercontent.com',
    iosClientId: '799043029018-ddodu4vvc4kt5okvd8ejh4vr867b2323.apps.googleusercontent.com',
    iosBundleId: 'com.example.oscar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqdVaH_-xKCnpg2-yS9MDCZpB_LcVZcfU',
    appId: '1:799043029018:web:2a4b936e245971c30429a3',
    messagingSenderId: '799043029018',
    projectId: 'homy-3693e',
    authDomain: 'homy-3693e.firebaseapp.com',
    databaseURL: 'https://homy-3693e-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'homy-3693e.appspot.com',
    measurementId: 'G-RQCFFDZC9K',
  );
}
